govuk-one-login/ipv-cri-lib

- src/main/java/uk/gov/di/ipv/cri/address/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/personidentity/PersonAddress.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/personidentity/PersonAddressType.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/personidentity/PersonIdentity.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/sharedclaims/Address.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/sharedclaims/BirthDate.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/sharedclaims/Name.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/sharedclaims/NamePart.java
- src/main/java/uk/gov/di/ipv/cri/address/library/domain/sharedclaims/SharedClaims.java
- src/main/java/uk/gov/di/ipv/cri/address/library/persistence/DynamoDbEnhancedClientFactory.java
- src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/personidentity/PersonIdentityDateOfBirth.java
- src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/personidentity/PersonIdentityItem.java
- src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/personidentity/PersonIdentityName.java
- src/main/java/uk/gov/di/ipv/cri/address/library/persistence/item/personidentity/PersonIdentityNamePart.java
- src/main/java/uk/gov/di/ipv/cri/address/library/service/AuditService.java
- src/main/java/uk/gov/di/ipv/cri/address/library/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/address/library/service/PersonIdentityMapper.java
- src/main/java/uk/gov/di/ipv/cri/address/library/service/PersonIdentityService.java
- src/main/java/uk/gov/di/ipv/cri/address/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/address/library/util/EventProbe.java
- src/test/java/uk/gov/di/ipv/cri/address/library/service/PersonIdentityMapperTest.java
- src/test/java/uk/gov/di/ipv/cri/address/library/service/PersonIdentityServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/address/library/service/SessionServiceTest.java
Add PersonIdentityService to enable user PII to be persisted to dynamo db and retrieved in an appropriate shape for sending to the third party knowledge-based-verification and fraud APIs.
[KBV-377](https://govukverify.atlassian.net/browse/KBV-377)
> KBV-377 - persist person identity

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/sharedclaims/NamePart.java
- src/test/java/uk/gov/di/ipv/cri/common/library/domain/sharedclaims/NamePartTest.java
Fix to avoid errors in CRIs when parsing NameParts with unexpected properties.
- [KBV-395](https://govukverify.atlassian.net/browse/KBV-395)
> KBV-395 Fix to avoid errors when parsing NameParts with unexpected properties

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEventTypes.java
Added new event types for the new KBV auditing
The audit service currently sends events using these constants.
This gets it working at the moment, however this will need to be revisited
- [KBV-106](https://govukverify.atlassian.net/browse/KBV-106)
> [KBV-106] Add new event types

- src/main/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifier.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/EventProbe.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifierTest.java
- Removed temporary logging implementation
- Changed Logger class log method to ensure the stacktrace is logged
- Added recursive logging of the exception cause
- Amended the JWTVerifier class to ensure exceptions are not being swallowed
A temporary implementation was quickly pushed to help resolve an issue in the integration environment.
Recursive logging of the exception cause was not present.
> BAU - log exception stacktrace and cause(s)

- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/DataStore.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/ListUtil.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationServiceTest.java
- `ConfigurationService` - Removed address CRI specific methods & redundant `getDynamoDbEndpointOverride` methods 
- `ListUtil` - corrected a sonar lint code smell
- `DataStore` - removed redundant static method: `getClient(URI endpointOverride)`
It's part of recent work to remove CRI-specifc code from common-lib
> BAU - ConfigurationService - remove redundant / CRI-specific methods

- src/main/java/uk/gov/di/ipv/cri/common/library/error/ErrorResponse.java
A toString() override was added to the ErrorResponse to enable both code and message to be rendered correctly within the Nimbus OAuth2Error
In updating to return response errors in the same way as core, the ErrorResponse was not being correctly interpreted as a string
> [BAU] - Add a "toString()" override for ErrorResponse

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEvent.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditServiceTest.java
TxMA have asked for a component id to be sent to TxMA.
See Jira story, which says:
> "component_id" requires adding to each event message - this is either the URI or short name (e.g. SPOT)
Send the CRI issuer uri as this value.
This will be a non-breaking change that CRIs will pick up when they use the merged Pr code.
- [KBV-567](https://govukverify.atlassian.net/browse/KBV-567)
> KBV-567 Send issuer to TxMA on component_id field

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEvent.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/Address.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/CanonicalAddress.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapperTest.java
- `AuditEvent` has 2 new fields: `restricted` for PII and `extensions` for event-specific data
- `AuditService` has new methods to allow PII and extensions data to be recorded when an audit event is sent
- `PersonIdentityMapper` has a new method to map from `PersonIdentityDetailed` to the summarised `PersonIdentity`
- 'Address' & `CanonicalAddress` removed Optional<Long> type as this doesn't get omitted when serialised when it is empty. Instead we get  "uprn": { "empty": true, "present": false }
To enable audit event metadata to be sent
- [KBV-567](https://govukverify.atlassian.net/browse/KBV-567)
> KBV-567 - Add metadata to audit events

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEvent.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEventContext.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEventUser.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/PersonIdentityDetailed.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/DataStore.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactory.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactoryTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditServiceTest.java
- Added `user` object to AuditEvent
- Overhauled AuditService implementation
- Refactored the DataStore based on amends made by the core team 
To enable user-specific audit data to be sent to TxMA
- [KBV-622](https://govukverify.atlassian.net/browse/KBV-622)
> Add user object to AuditEvent

- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
Passing in configurationService into AuditService and SessionService
would make ServiceRegistry less complex.
See https://github.com/alphagov/di-ipv-cri-kbv-api/pull/142
> KBV-705: Pass in configurationService

- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEventUser.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/SessionItem.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactory.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactoryTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
Relays PersistentSessionId and ClientSessionId from SessionService/SessionRequest to AuditService/AuditEventUser via SessionItem.
The allows PersistentSessionId and ClientSessionId to appear in the user section of AuditEvents.
PersistentSessionId= "persistent_session_id"
ClientSessionId = "govuk_signin_journey_id" 
ClientSessionId follows [IPVAuthorisationService](https://github.com/alphagov/di-authentication-api/pull/2183/files) for variable naming.
Linked with [Common-Lamdas 20](https://github.com/alphagov/di-ipv-cri-common-lambdas/pull/20)
- [LIME-45](https://govukverify.atlassian.net/browse/LIME-45)
- [ADR-0039](https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0039-govuk-signin-journey-id.md)
- [RFC-0023](https://github.com/alphagov/digital-identity-architecture/ …
> LIME-45 Relay PersistentSessionId and ClientSessionId to AuditEventUser.

- src/main/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationServiceTest.java
Set secrets manager secret name prefix to env var `SECRET_PREFIX` and fall back to `AWS_STACK_NAME`.
Our lambdas currently expect to read secrets from a path that is prefaced with the stack name .e.g.
`/${AWS::StackName}/experian/iiq-url`
Change this to to:
`/${SecretPrefix}/experian/iiq-url`
where $SecretPrefix can be supplied as a parameter to the stack.
Also see https://github.com/alphagov/di-ipv-cri-kbv-api/pull/152
To read secrets in secrets manager that have a default name across deployed stacks, so that these don’t have to be set per stack
- [KBV-795](https://govukverify.atlassian.net/browse/KBV-795)
> KBV-795 Set secrets manager secret name prefix to env var 'SECRET_PREFIX'

- README.md
- build.gradle
- deploy/buildspec.yaml
* Add a Gradle task to sign and publish CRI common-libs as a jar to maven central
* Add an AWS CodeBuild spec for run the gradle task above
Run the signing and publishing of common-cri-libs from within AWS in a CodePipeline, so we can store secrets like signing private keys and account credentials in AWS Secrets Manager.
This is preferred to storing these secrets in Github as repo secrets.
- [OJ-887](https://govukverify.atlassian.net/browse/OJ-887)
> OJ-887 Gradle task and AWS CodeBuild spec for publishing CRI common-libs to maven central

- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationServiceTest.java
- A `commonParameterPrefix` field has been added to the `ConfigurationService`.
- New methods `getCommonParameterValue` / `getParameterValueByAbsoluteName`
- The change has been made in a backwards compatible manner. The `commonParameterPrefix` field will default to the current stack name if the environment variable is not present.
- This field will enable CRI-specific stacks to refer to SSM parameters that are prefixed with the common stack name.
- [OJ-788](https://govukverify.atlassian.net/browse/OJ-788)
> Add common-parameter-prefix to ConfigurationService

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/EventProbe.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
We need to be able to track user journeys across auth, core and CRIs.
Save `govuk_signin_journey_id` and `persistent_session_id` to CRI log messages.
The conditions for this are:
* client like IPV Core has sent these ids in the Authorization JAR to a CRI
* the CRI has interacted with the session DynamoDB table during a lambda invocation
* The lambda is writing a log message or exception
A new method on EventProbe has also been added to allow us to log messages, not just exceptions.
Lambdas that use this version should set the `clearState` attribute on the `@Logging` annotation i.e. `@Logging(clearState = true ....)`
Add govuk_signin_journey_id and persistent_session_id to structured log messages. 
Help us with 2nd-line DI support to trace a user journey.
- …
> OJ-930 Save journey ids from CRI client to structured logging context

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/SessionItem.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
Save Client Ip Address to session-di-ipv-cri-kbv-* Table. 
created new column in  session-di-ipv-cri-kbv-* Table and save the IP address from session.
To reuse IP address of client to send to TXMA.
- [OJ-924](https://govukverify.atlassian.net/browse/OJ-924)
> OJ-924: Save client ip address provided to /session API call

- .secrets.baseline
- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationServiceTest.java
We identified that too much lambda time is spent looking up SSM params and Secrets Manager secrets, as the current [powertools](https://awslabs.github.io/aws-lambda-powertools-java/utilities/parameters/) cache TTL is 5 seconds. We want to cache params and secrets for a longer time, and make our lambdas run faster.
This fix is to increase this timeout to 5 minutes by default, and set the value explicitly via the env var `CONFIG_SERVICE_CACHE_TTL_MINS`.
- [OJ-957](https://govukverify.atlassian.net/browse/OJ-957)
> OJ-957 Cache SSM params and secrets for longer

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/KMSSigner.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/KMSSignerTest.java
Convert the KMS der signature format into concat format.
By default KMS the signature is in DER format. We have being using this and this is currently incompatible with the specs. The correct format should be R||S format (aka CONCAT format) this PR is ensure compatibility 
Related
[DCP-343](https://govukverify.atlassian.net/browse/DCP-343)
- [OJ-982](https://govukverify.atlassian.net/browse/OJ-982)
> OJ-982: Update vc signature to concat format

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/error/OauthErrorResponse.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/SessionItem.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
added dlAttemptCount to sessionItem in order to track attempts in drivingLicenceCri, also added OauthErrorResponse class for returning accessDenied error to IpvCore when a user escapes their journey.
For integration with Driving licence Cri and for escape route error handling
> LIME-147 - Adding dlRetry and OauthErrorResponse to common lib

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/helper/LogHelper.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifier.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifierTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
Shifted passport sessionItem functionality and fields into common library, for integration of passport cri into common
So that passport session can be handled by common
- [LIME-125](https://govukverify.atlassian.net/browse/LIME-125)
> LIME-125 - Moving Passport session items into common

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
- Added `VerifiableCredentialClaimsSetBuilder` class
- To centralise the creation of the verifiable credential JWT claims
- [OJ-976](https://govukverify.atlassian.net/browse/OJ-976)
> OJ-976 - Add common VC JWT claims set builder

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/EventProbe.java
- Added new method to the `EventProbe` class to add a field to the logging context
- To enable the journey id to be recorded against log entries
- [OJ-993](https://govukverify.atlassian.net/browse/OJ-993)
> OJ-993 - Provide mechanism to add field(s) to logging context

- RELEASE_NOTES.md
- build.gradle
- settings.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/ClientConfigurationService.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/HttpHeaders.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/IpvCoreStubClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CriTestContext.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/util/URIBuilder.java
- Added test fixtures to provide the common lambdas/ipv-core-stub API clients and cucumbers steps
- Removed the inconsistent use of the plugins in `build.gradle`
- To provide an initial framework for the CRI integration tests
- To remove the duplication of code present in the address/kbv cri integration tests modules
- Note, the majority of code introduced in this PR has come from the `kbv-api` repository
- [OJ-1075](https://govukverify.atlassian.net/browse/OJ-1075)
> OJ-1075 - Integration testing - Add common clients and cucumber steps

- .github/workflows/pre-merge-checks.yml
- .pre-commit-config.yaml
- .secrets.baseline
Address, Fraud and KBV SSM parameter deployment workflows have been updated:
* Deprecated GHA actions have been updated to the newer versions.
* setup-sam fix has been applied
Primarily to apply the setup-sam fix so that the workflows are not broken.
(https://github.com/aws/aws-sam-cli/issues/4527)
Secondly in preparation for GitHub to remove the deprecated functionality.
- [OJ-1146](https://govukverify.atlassian.net/browse/OJ-1146)
[OJ-1146]: https://govukverify.atlassian.net/browse/OJ-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-1146 workflow deprecations and sam fix

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEventType.java
Added RESPONSE_RECEIVED to the AuditEventType
This is to replace THIRD_PARTY_REQUEST_ENDED
> LIME-406 - Added RESPONSE_RECEIVED to the AuditEventType

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/deserializers/PiiRedactingDeserializer.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/deserializers/PiiRedactingDeserializerTest.java
The code redacts sensitive fields when an error occurs parsing Json. Use this by registering with objectMapper
```
SimpleModule redactionModule = new SimpleModule();
this.objectMapper = new ObjectMapper();
redactionModule.addDeserializer(
SharedClaims.class,
new PiiRedactingDeserializer<>(sensitiveFields, SharedClaims.class));
objectMapper
.registerModule(redactionModule)
```
On rare ocassions an error can occur during JSON parsing for example in the SharedClaim above, these errors are thrown to the [EventProbe](https://github.com/alphagov/di-ipv-cri-lib/blob/main/src/main/java/uk/gov/di/ipv/cri/common/library/util/EventProbe.java#L36) this could result in PII leakage. This PR introduces an objectMapper module that intercepts the deserialization process when an error occurs and redacts …
> OJ-1305: Added code to redact sensitive fields

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
see: https://govukverify.atlassian.net/browse/OJ-1313
The inclusion of expiry date on the VC is can be optionally engaged or switched off
Decison to implement time-based identity check validity policy based (in the first place) on issuance dates, rather than hard-coded expiry dates in verifiable credentials (VCs). This decision is recorded in [ADR 76 (VC lifetime)](https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0076-vc-lifetime.md).
- [OJ-1313](https://govukverify.atlassian.net/browse/OJ-1313)
- /release-flags/vc-expiry-removed
[OJ-1313]: https://govukverify.atlassian.net/browse/OJ-1313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj1313: removed vc expiry in the common claimset builder

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/ClientConfigurationService.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
Facilitate the ability to be able to run the command https://github.com/alphagov/di-ipv-cri-kbv-api#run-integration-tests by changing IPV_CORE_STUB_URL to point to the new aws stub url i.e. https://di-ipv-core-stub.london.cloudapps.digital/
doing this would make it easier to know what needs to be added when amending corresponding https://github.com/alphagov/di-ipv-cri-kbv-api/blob/main/.github/workflows/pre-merge-integration-test.yml
Added a `ipvCoreStubClientId` which allows overriding the stub id from `ipv-core-stub`
The move from PAAS to AWS introduces a new stub Id `ipv-stub-core-aws-build` or `ipv-stub-core-aws-prod`
depending on the environment
- [OJ-1522](https://govukverify.atlassian.net/browse/OJ-1522)
New Environment variable `DEFAULT_CLIENT_ID`
Consumers such as (KBV or …
> OJ-1522: added default client id

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
Added id field to VerifiableCredentialClaimsSetBuilder which will require VeriableCredential issuers to specify a UUID
logic is introduced via a `release_flag` which involves checking for the presence and of the value of `/release-flags/vc-contains-unique-id` contains "true" if the release above release flag is not present or is any other value it returns false.
Implying VC have not yet enabled to the feature flag to include unique id
https://github.com/alphagov/digital-identity-architecture/blob/main/adr/0079-unique-identifier-for-verifiable-credential.md#option-6---preferred-optionIn order to be able to distinguish one Verifiable Credential (VC) from another VC it will be necessary for VCs to be able to be uniquely identifiable
- …
> OJ-1422: add unique id to vc

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
Fix for previous [PR](https://github.com/alphagov/di-ipv-cri-lib/pull/244) two things were wrong
- The `id` is a to level attritube of the `jwt` not inside the `vc` element
- The name is `jti` and not `id`
see: https://github.com/alphagov/digital-identity-architecture/blob/7c90be0db85a3a3093c766d845d5f278a3d86e16/rfc/0045-claimed-identity-cri.md?plain=1#L217
Miss-intepretation of the indentifier [JSON-LD ](https://www.w3.org/TR/vc-data-model/#example-a-relationship-credential-issued-by-a-child)refers to identifier as `id` whereas when verifiable-credential are expressed as [jwt](https://www.w3.org/TR/vc-data-model/#example-jwt-payload-of-a-jwt-based-verifiable-credential-using-jws-as-a-proof-non-normative) the id is referred to as `jti` 
- …
> Oj-1422: add jti to vc using uniqueuuid

- CODEOWNERS
- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
Making package access public for the person identity mapper
To allow testing in other services that use the common lib
> LIME-883: Updating access of the person identity mapper so we can use the person identity service in tests

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/Address.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityDetailedBuilder.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityDetailedBuilderTest.java
see https://github.com/govuk-one-login/ipv-cri-address-api/pull/885
Added a constructor to Address Domain object to allow, converting to from CanonicalAddress to Address
This is done to avoid using the PersonIdentityMapper
Also added Added `PersonIdentityDetailedBuilder` to be used with the AuditContext for AddressCri where
nameparts and birthdate are not required and would have required passing nulls as follows
**Before**
```
new AuditEventContext(
new PersonIdentityDetailed(
null,
null,
addressService.mapCanonicalAddresses(
addressItem.getAddresses()))
```
`After`
```
new AuditEventContext(
PersonIdentityDetailedBuilder.builder()
.withAddresses(
addressItem.getAddresses().stream()
.map(Address::new)
.collect(Collectors.toList()))
.build())
```
- …
> OJ-2240: prep add address vc restricted fields

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEvent.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactory.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactoryTest.java
Amended audit event timestamps to now reflect milliseconds as requested from TxMA
> LIME-1019 - Amending audit event timestamps to be in milliseconds

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/DeviceInformation.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/PersonIdentityDetailed.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactory.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditEventFactoryTest.java
Adds `device_information`  to restricted if the header is present
To allow the inspection of user audit information and track possible fraud
With header sent
Without
- [DCP-3351](https://govukverify.atlassian.net/browse/DCP-3351)
- [DCP-3352](https://govukverify.atlassian.net/browse/DCP-3352)
[DCP-3351]: https://govukverify.atlassian.net/browse/DCP-3351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCP-3352]: https://govukverify.atlassian.net/browse/DCP-3352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DCP-3351: Adds device_information  to restricted if the header is present

- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
Added new step definition for posting session request to include the `Txma-Audit-Encoded` header to be referenced in the address repo.
To enable testing within the `Header` value within address-api repo 
- [OJ-2546](https://govukverify.atlassian.net/browse/OJ-2546)
[OJ-2546]: https://govukverify.atlassian.net/browse/OJ-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2546: Update step definition to include txma header in session endpoint

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
Added new step definition for posting session request to include the `Txma-Audit-Encoded` header to be referenced in the address repo.
To enable testing within the `Header` value within address-api repo 
- [OJ-2546](https://govukverify.atlassian.net/browse/OJ-2546)
[OJ-2546]: https://govukverify.atlassian.net/browse/OJ-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2546: Update header for session endpoint

- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/ListUtil.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/ListUtilTest.java
**`ListUtil`:**
- Make ListUtil a static class
This doesn't need to be instantiated as it only contains static util methods
- Add tests
**OJ-2546:**
- Add list utility methods to use in SQS tests
- Add a method to ListUtil to split a list into batches
- Add a method to ListUtil to construct a list excluding elements from another list using a custom comparator
- Add a method to ListUtil to exclude elements from a list using a custom comparator
- Add a method to ListUtil to merge two lists without duplicating elements, using a custom comparator
- Add a method to ListUtils to determine whether a list contains an object using a custom comparator
> OJ-2546: Add list utils to allow for adding and removing unique elements using custom comparators

- build.gradle
- src/test/java/uk/gov/di/ipv/cri/common/library/util/ListUtilTest.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/aws/SQSHelper.java
- Add an SQS helper for integration tests
The helper allows to retrieve and delete messages from SQS queues in a predictable and controlled manner.
_This needs some tests (to be added separately)._
- Add AWS SSO modules to testFixtures to allow projects using the library to authenticate to AWS when running integration tests
The AWS SDK can automatically authenticate without the need to copy and paste secrets and keys every hour.
> OJ-2546: Add SQS helper for integration tests

- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/aws/CloudFormationHelper.java
CloudFrontHelper in Utils folder:
The helper allows to retrieve information from stacks, such as input or output values.
Created a  CloudFrontHelper class
[OJ-2546](https://govukverify.atlassian.net/browse/OJ-2546):
Add CloudFormationClient method to use in SQS tests
Add a method to retrieve stack outputs key and values from cloudformation to use in SQS tests
Add a method to retrieve stack parameters key and values from cloudformation to use in SQS tests
Update dependency in build.gradle to use version 2.x
To enable testing SQS in different CRIs
[OJ-2546]: https://govukverify.atlassian.net/browse/OJ-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2546: Add a CloudFormation helper for integration tests

- RELEASE_NOTES.md
- build.gradle
- src/test/java/uk/gov/di/ipv/cri/common/library/util/ListUtilTest.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/aws/CloudFormationHelper.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/aws/SQSHelper.java
**OJ-2546: Make SQS helper work better with shared queues and concurrent clients**
- Process the queue in rounds until the targeted messages have been received or all the messages in the queue have been received
- Release unwanted messages when the queue is empty to prevent blocking between concurrent clients
- Replace the static timeout and calculate a timeout for each round based on the current queue size
- Replace the `throwOnTimeout` param with the `try...` pattern for method naming
- Use long and double types for timeout calculations to ensure correct values are used
- Use nested loops when processing the queue to simplify the logic
- Use maps instead of lists to keep messages in memory and simplify the logic to get distinct messages by ID
---
Minor updates to the SQS and CF test …
> OJ-2546: Make SQS helper work better with shared queues and concurrent clients

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/EvidenceRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/SessionItem.java
- src/test/java/uk/gov/di/ipv/cri/common/library/persistence/SessionItemTest.java
Sessions can have a optional `evidence_request` column in DynamoDB and so this PR ensures our SessionItem can access that column.
For KBV CRI, we want the `verification_score` value from the `evidence_request` column to be within the VC.
- [OJ-2612:](https://govukverify.atlassian.net/browse/OJ-2612)
> OJ-2612: Add EvidenceRequest to Session

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/PersonIdentityDetailed.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/ListUtil.java
This PR fixes the Javadoc warnings that occur when running gradle build. The warnings are primarily, missing @param docs or @return docs
> BAU: Fix Javadoc warnings

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/IpvCoreStubClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
Updated shared claims endpoint to include evidence request parameters to update the verificationScore and strengthPolicy
To enable integration tests in KBV CRI
- [OJ-2612](https://govukverify.atlassian.net/browse/OJ-2612)
[OJ-2612]: https://govukverify.atlassian.net/browse/OJ-2612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2612: Update shared claims to include Evidence Request parameters

- .gitignore
- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AccessTokenService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AuditService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/ClientProviderFactory.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AuditServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/ConfigurationServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/ClientProviderFactoryTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
- Remove default constructors of
- - ConfigurationService
- - SessionService
- - AccessTokenService
- - AuditService
Add ClientProviderFactory to enable a single source of clients for services
Add AwsCrtHttpClient as dependancy and switch to it as the single http client used by all aws clients provided by ClientProviderFactory.
ClientProviderFactory sets awsRegion, environmentVariableCredentialsProvider and defaultsMode on each client to reduce Java lambda start up times.
ClientProviderFactory shares a single AwsCrtHttpClient with each client to further reduce reduce Java lambda start up times and resource usage.
Clients provided by ClientProviderFactory can then be reused by any CRI specific services avoiding duplicate clients and sharing the same clients as the common services and …
> LIME-1071 Java SSM parameter and common service optimisation

- RELEASE_NOTES.md
- build.gradle
Remove versions specified for the main Jackson dependencies and defer to the ones pull in from `software.amazon.awssdk:bom`.
There is a breakage in a later jackson version, which crashes in the sdk classes which expect the older versions. 
Note : jackson-datatype-jsr310 and jackson-datatype-jdk8 are not in the aws sdk and are custom dependencies these version have been set at the aws pom versions to avoid a mismatch.
- [LIME-1071](https://govukverify.atlassian.net/browse/LIME-1071)
[LIME-1071]: https://govukverify.atlassian.net/browse/LIME-1071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Release 3.0.1 - LIME-1071 Correct conflicting jackson dependencies

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactory.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilder.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactoryTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/VerifiableCredentialClaimsSetBuilderTest.java
Add a overrideJti method to the builder to allow access to the JwtClaimset in order to set dummy value for `jti` to help in contract tests
See: https://github.com/govuk-one-login/ipv-cri-address-api/blob/5cf485eb0ce5bc637accc1a2a8929153ee2235c6/lambdas/issuecredential/src/test/java/uk/gov/di/ipv/cri/address/api/handler/pact/SingleAddressBuildNumberVcTest.java#L107
Contract testing means fixing certain values such as the `jti` which is randomly generated.
Expected values for contract-test nbf, exp and jti can be specified as follows:
```
environmentVariables.set(ENV_VAR_FEATURE_FLAG_VC_CONTAINS_UNIQUE_ID, "override");
Clock clock = Clock.fixed(Instant.parse("2099-01-01T00:00:00.00Z"), ZoneId.of("UTC"));
VerifiableCredentialClaimsSetBuilder claimsSetBuilder =
new …
```
> OJ-2650: add overrideJti to builder

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactory.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactoryTest.java
- Added new methods to SignedJWTFactory to allow CRIs to add opaque KID to JWT headers for VCs
- As requested in RFC 83 - https://github.com/govuk-one-login/architecture/blob/main/adr/0083-publishing-signing-keys-for-vcs.md#key-resolution-and-the-web-did-method
> LIME-1202 - Including Opaque KID in JWT headers for VCs

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactory.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactoryTest.java
KBV recently updated to use KID from the 3.0.4 update. Reported that the format was wrong as the issuer contained https:// and then a colon instead of a hash. Example - This will now produce: did:web:Issuer#HashedKeyID instead of did:web:Issuer:HashedKeyID
v.3.0.5
KBV recently updated to use KID from the 3.0.4 update. Reported that the format was wrong as the issuer contained https:// and then a colon instead of a hash. Example - This will now produce: did:web:Issuer#HashedKeyID instead of did:web:Issuer:HashedKeyID
- [OJ-2720](https://govukverify.atlassian.net/browse/OJ-2720)
[OJ-2720]: https://govukverify.atlassian.net/browse/OJ-2720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2720: Kid fix for JWT header

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/EventProbe.java
Created a new method counterMetric that accepts a Unit as an additional parameter.
There was no way for us to set the unit of a metrics e.g. seconds.
> BAU: New `counterMetric` with unit parameter

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/SessionRequest.java
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/SessionItem.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/persistence/SessionItemTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
Context field added to SessionRequest and SessionItem.
To allow context claims to be stored with the session. 
- [OJ-2812](https://govukverify.atlassian.net/browse/OJ-2812)
[OJ-2812]: https://govukverify.atlassian.net/browse/OJ-2812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2812: Context field added to SessionRequest and SessionItem

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/IpvCoreStubClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
Refactored `getClaimsForUser` so there is only one place to add changes rather than two i.e a map of all parameters needed for method is added as part of the request in the new common step. Instead of added and common step and a new variant of `getClaimsForUser` in `IpvCoreStubClient` as previously done
[IpvCoreStubClient.java](https://github.com/govuk-one-login/ipv-cri-lib/compare/OJ-2813-add-userIdentity-with-context?expand=1#diff-1ade1c40794f3abbbe229e554c7527d8b0310b521c260354fbc79126a08f0ed0) is referenced by [CommonSteps.java](https://github.com/govuk-one-login/ipv-cri-lib/compare/OJ-2813-add-userIdentity-with-context?expand=1#diff-bdbd388801bc0170df4961794736e818ec8c4508fe4bf36fb6492cd254bd1aca) and not used elsewhere.
The common steps defined are used …
> OJ-2813: add user identity with context

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/DataStore.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/AccessTokenService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/AccessTokenServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapperTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/KMSSignerTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/SignedJWTFactoryTest.java
- Release 3.1.3
- Extract DVLA postcode using a simple trim on the full address (mpv).
- Extract DVA postcode using expected NI postcode prefix (mpv).
- Remove Driving permit from existing test (address invalid to be sent with driving permit)
- Add dedicated MapDrivingPermitSharedClaimsToPersonIdentityItem to handle postcode extraction tests.
- - Adds test for known issue with mvp trim approach.
- Update googleJavaFormat due to linting failures
- Lint files with 1.18.1
- Bump aws sdk version to 2.28.2
- - Add missing ssm gradle configuration
- Replace hidden DynamoDbClientBuilder builder in Datastore with one provided from the clientProviderFactor.
- - DataStore.getClient() marked as deprecated, as this will lead to a unique client per Datastore and prevents the sharing of a single …
> LIME-1312 Extract postcode from DrivingPermit fulladdress

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/item/CanonicalAddress.java
Add addressRegion to CanonicalAddress
New field for OneLogin address schema to support International Addresses
> OJ-2816: Add addressRegion to CanonicalAddress

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapperTest.java
Loosen Driving Permit Postcode extraction from DVA licenses
Extraction was preventing test data being used
- [LIME-1312](https://govukverify.atlassian.net/browse/LIME-1312)
[LIME-1312]: https://govukverify.atlassian.net/browse/LIME-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1312 Loosen Driving Permit Postcode extraction from DVA licenses

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/AuditEvent.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/DeviceInformation.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/PersonIdentityDetailed.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JsonSchemaValidator.java
- src/test/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/RawAuditEventTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/TestHarnessResponseTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JsonSchemaValidatorTest.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/ClientConfigurationService.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/TestResourcesClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/domain/RawAuditEvent.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/domain/TestHarnessResponse.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CriTestContext.java
- Updated audit event tests to use the new test harness events endpoint
- Added AWS credentials to sign the HTTP request for the events endpoint 
- Removed the previous SQS and cloudformation usages for TxMA step definitions in Address repo
Tested the changes in using publishToMavenLocal() command and tests are all passing:
To use the test harness to assert that TxMA events are written by CRIs in a common way. To support the testing of the cloudfront headers, this solution is being used in other parts of the programme. 
- [OJ-2739](https://govukverify.atlassian.net/browse/OJ-2739)
[OJ-2739]: https://govukverify.atlassian.net/browse/OJ-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2739: Update audit event tests to use test harness

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/personidentity/Address.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapper.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/PersonIdentityMapperTest.java
Following on from 3.2.0 release, this adds addressRegion to Address
Refactored shouldMapPersonIdentityItemToPersonIdentityDetailed as the test had too many asserts and was flagging as a code smell. 
Adds SQ exclusion for `Address.java`. This is flagging duplication with CanonicalAddress. 
`property "sonar.cpd.exclusions", "**/di/ipv/cri/common/library/domain/personidentity/Address.java"`
Note: I did attempt `// NOSONAR` on the specific lines I have added to avoid excluding the whole file but it did not work. 
Also add the field to Address object. 
- [OJ-2816](https://govukverify.atlassian.net/browse/OJ-2816)
[OJ-2816]: https://govukverify.atlassian.net/browse/OJ-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2816: Add addressRegion to Address

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/TestResourcesClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
`sendEventRequest` method now accepts `eventName` parameter as an additional filter to be used in feature file
To assist with test harness implementation in kbv
- [OJ-2737](https://govukverify.atlassian.net/browse/OJ-2737)
[OJ-2737]: https://govukverify.atlassian.net/browse/OJ-2737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Oj 2737 test harness tests

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/persistence/DataStore.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/ClientProviderFactory.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/ClientProviderFactoryTest.java
ClientProviderFactory selects the appropriate AwsCredentialsProvider to use for AWS clients (EnvironmentVariableCredentialsProvider/ContainerCredentialsProvider.builder) based the current init environment - lambda snap start container or lambda run-time init environment.
Java SnapStart creation runs within a container and can only access credentials via ContainerCredentialsProvider. With non-snap start code able to access EnvironmentVariableCredentialsProvider.
This provides support for snap-start and non-snap-start Java lambda configurations.
- [LIME-1384](https://govukverify.atlassian.net/browse/LIME-1384)
[LIME-1384]: https://govukverify.atlassian.net/browse/LIME-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIME-1384 ClientProviderFactory - select an AwsCredentialsProvider based on the current runtime environment

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
Added a _empty_ check to the `sessionId` in `validateSession` prior to calling DDB, and returns a `SessionNotFoundException` instead of a `DynamoDbException`.
If `validateSession` was called with an 'empty' String it would still search DynamoDB and result in a `DynamoDbException` - Supplied AttributeValue is empty, must contain exactly one of the supported datatypes
- [OJ-2821](https://govukverify.atlassian.net/browse/OJ-2821)
[OJ-2821]: https://govukverify.atlassian.net/browse/OJ-2821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2821: Check sessionId is present before validating session

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/exception/RetryException.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/retry/RetryConfig.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/retry/RetryManager.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/retry/Retryable.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/SessionServiceTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/retry/RetryManagerTest.java
* Added a generic class to allow for retry logic
* Added retries to SessionService#getSessionByAccessToken
We use a GSI in DynamoDB, which provides eventual consistency, meaning reads from the GSI may not immediately reflect the latest record. To address this, we implemented a retry mechanism in getSessionByAccessToken, retrying up to 3 times within 1 second to ensure the record is retrieved.
**Background on GSI**:
DynamoDB provides two consistency models for reads: eventually consistent and strongly consistent. When you read data from a GSI, the default behaviour is eventual consistency, meaning that after a write operation (e.g., an update, insert, or delete), the GSI may not immediately reflect the latest changes. This happens because GSIs are updated asynchronously in the background, …
> OJ-3087: Add retry mechanism and add retires to SessionService#getSessionByAccessToken

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/jwks/JWKS.java
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/jwks/Key.java
- src/main/java/uk/gov/di/ipv/cri/common/library/exception/JWKSRequestException.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifier.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCache.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkRequest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCacheTest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JwkRequestTest.java
* Added  code to invoke the `/.well-known/jwks.json` endpoint
* Added code to cache the response + respect the Cache-Control header
* Updated JWTVerifier to use the key from the jwks endpoint - will default to previous behaviour on failure
**Screenshots**
AccessTokenFunction Log Group:
SessionFunction Log Group:
When Disabled:
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2972: use public JWKs endpoint to verify JWTs

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/jwks/JWKS.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCache.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCacheTest.java
Added a null check to getSigningKeyForKid
Noticed a NPE when the request to the public jwk endpoint fails. 
- [KBV-2972](https://govukverify.atlassian.net/browse/KBV-2972)
> OJ-2972: fix NPE with  getSigningKeyForKid

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/exception/JWKSRequestException.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkRequest.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JwkRequestTest.java
Added a status code check to callJWKSEndpoint
So that we're handling errors better. 
- [OJ-2972](https://govukverify.atlassian.net/browse/OJ-2972)
[OJ-2972]: https://govukverify.atlassian.net/browse/OJ-2972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-2972: Add a status code check to callJWKSEndpoint

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/CommonApiClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/StubClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/client/TestResourcesClient.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/CommonSteps.java
- Added the `/start` request endpoint to use for the default and overwritten test scenarios
- Added new `/token` and `/authorization` endpoint for the test resource client (so that it does not impact existing tests)
- Updated the `/events` endpoint to retry the request till the request body is there, to reduce errors
- Created a new Stub Client file to generate the client assertion for the `/token` endpoint to use in replace of ipvCoreStubClient file
To use the headless, typescript core stub that has a /start endpoint that returns a JWT that can be used to start a session in any CRI frontend.
- [OJ-2677](https://govukverify.atlassian.net/browse/OJ-2677)
[OJ-2677]: https://govukverify.atlassian.net/browse/OJ-2677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> OJ-2677: Update tests to use new headless core stub

- RELEASE_NOTES.md
- build.gradle
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/config/ApiGatewayConfig.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/config/EnvironmentConfig.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/helpers/HttpClientHelper.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/helpers/HttpResponseHelper.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/WellKnownJwksSteps.java
Created `.well-known/jwks.json` for Address-cri see https://github.com/govuk-one-login/ipv-cri-address-api/pull/1276
This PR would enable to ability to run an integration-test for this new endpoint in the address-cri as shown in the screen-shot below
- [OJ-2969:](https://govukverify.atlassian.net/browse/OJ-2969:)
> OJ-2969: Integration jwks endpoint

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/SessionService.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/retry/RetryManager.java
* Updated RetryManager to log the first attempt and if it succeeded.
* Updated SessionService#getSessionByAccessToken and set the delayBetweenAttempts to 500ms
When querying the session table by access token, it uses a GSI and it takes around a second for the base table to update. Previously, we waited 200ms and went up exponentially but with 3 attempts, the total time we spent retrying was 600ms (since attempt 0 isn't sleeping attempt). 
- [OJ-3180](https://govukverify.atlassian.net/browse/OJ-3180)
[OJ-3180]: https://govukverify.atlassian.net/browse/OJ-3180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3180: Increase delayBetweenAttempts when calling getSessionByAccessToken

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/domain/jwks/JWKS.java
- src/main/java/uk/gov/di/ipv/cri/common/library/service/JWTVerifier.java
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCache.java
- src/test/java/uk/gov/di/ipv/cri/common/library/util/JwkKeyCacheTest.java
JWKS Endpoints will now be retrieved from SSM instead of a single ENV variable to support different clients providing different endpoints. 
Caching has been updated so each endpoint is cached instead of a single cached JWKS.
The CRIs need to consume the public signing key from the service that signed the JWT.
- [OJ-3175](https://govukverify.atlassian.net/browse/OJ-3175)
[OJ-3175]: https://govukverify.atlassian.net/browse/OJ-3175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OJ-3175: Retrieve JWKS endpoint URLs from SSM

- .github/workflows/run-unit-tests.yml
- .github/workflows/scan-repo.yml
- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkRequest.java
Removed `Thread.currentThread().interrupt();` as it was causing outgoing DynamoDB requests to fail with an `AbortedException` since the thread had been interrupted. 
- [Oj-3218](https://govukverify.atlassian.net/browse/OJ-3218)
> fix: remove Thread#interrupt from JwkRequest

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/util/JwkRequest.java
Use a new HttpClient for each request in JwkRequest
`JWKSRequestException called with cause java.io.IOException: /169.254.76.1:37802: GOAWAY received` - suspected that the connection has been idling too long and AWS closes the connection.
> Use a new HttpClient for each request in JwkRequest

- RELEASE_NOTES.md
- build.gradle
- src/main/java/uk/gov/di/ipv/cri/common/library/service/KMSRSADecrypter.java
- src/test/java/uk/gov/di/ipv/cri/common/library/service/KMSRSADecrypterTest.java
- src/testFixtures/java/uk/gov/di/ipv/cri/common/library/stepdefinitions/WellKnownJwksSteps.java
Update KMSRSADecrypter 
KMSRSADecrypter in common lambda has legacy flag updates
So that eventually we have just one copy i.e. the one in the library, which common-lambda can reference
- [OJ-3210:](https://govukverify.atlassian.net/browse/OJ-3210)
> OJ-3210: Update KMSRSADecrypter 
